/*
 * generated by Xtext 2.22.0
 */
package org.xtext.arithmetic.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ArithmeticUiModule extends AbstractArithmeticUiModule {

	public ArithmeticUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
