/*
 * generated by Xtext 2.22.0
 */
package org.xtext.arithmetic.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.arithmetic.ui.internal.ArithmeticActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class ArithmeticExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(ArithmeticActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		ArithmeticActivator activator = ArithmeticActivator.getInstance();
		return activator != null ? activator.getInjector(ArithmeticActivator.ORG_XTEXT_ARITHMETIC_ARITHMETIC) : null;
	}

}
