/*
 * generated by Xtext 2.22.0
 */
package org.xtext.arithmetic;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ArithmeticStandaloneSetup extends ArithmeticStandaloneSetupGenerated {

	public static void doSetup() {
		new ArithmeticStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
