/*
 * generated by Xtext 2.22.0
 */
package org.xtext.arithmetic.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.arithmetic.ArithmeticRuntimeModule;
import org.xtext.arithmetic.ArithmeticStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ArithmeticIdeSetup extends ArithmeticStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ArithmeticRuntimeModule(), new ArithmeticIdeModule()));
	}
	
}
