/*
 * generated by Xtext 2.22.0
 */
package org.xtext.arithmetic.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractArithmeticScopeProvider extends DelegatingScopeProvider {
}
